config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
  }

  namespace :dashboard do
    get 'pages/home'
    resources :rooms, only: %i[index]
    resources :exams, only: %i[index]
    resources :levels, except: %i[index]
    resources :questions
    resources :results, only: %i[index new create]
    root to: "pages#home"
  end

  authenticated :user do
    root to: 'dashboard/pages#home', as: 'authenticated_root'
  end

  unauthenticated :user do
    root to: 'pages#home', as: 'unauthenticated_root'
  end
end

app/models/exam.rb
class Exam < ApplicationRecord
  before_validation :assign_title
  belongs_to :teacher, class_name: 'User'
  belongs_to :school
  has_one :level
  has_many :results

  validates_presence_of :title

  def numbers_of_exams
    Exam.all.count
  end

  def can_create_exam?(school_id)
    School.find(school_id).exams.count < 9
  end

  private

  def assign_title
    self.title = "Exam #{numbers_of_exams + 1}"
  end
end

app/controllers/dashboard/dashboard_controller.rb
module Dashboard
  class DashboardController < ApplicationController
    before_action :authenticate_user!
    layout 'dashboard'
  end
end

app/controllers/dashboard/exams_controller.rb
module Dashboard
  class ExamsController < Dashboard::DashboardController
    before_action :set_exam, only: %i[show]

    def index
      @exams = current_user.student_role? ? current_user.school.exams - current_user.school.exams.joins(:results).where(results: {student_id: current_user.id, taken: true})
                   : current_user.school.exams.includes(%i[teacher])
    end

    def show
      @levels = @exam.levels
    end

    private

    def set_exam
      @exam = Exam.find(params[:id])
    end
  end
end

app/controllers/dashboard/levels_controller.rb
module Dashboard
  class LevelsController < Dashboard::DashboardController
    load_and_authorize_resource
    before_action :set_level, only: %i[show edit update destroy]

    def index
      @levels = Level.all
    end

    def show; end

    def new
      @level = Level.new
    end

    def edit; end

    def create
      @level = Level.new(level_params)
      @exam = Exam.new(teacher_id: current_user.id)
      school_id = current_user.school.id

      if @exam.can_create_exam?(school_id)
        @exam.school_id = school_id
        @exam.teacher_id = current_user.id
        @exam.save

        @level.exam = @exam
        @level.teacher_id = current_user.id if current_user.teacher_role? || current_user.superadmin_role?

        if @level.save
          redirect_to dashboard_level_url(@level), notice: 'Exam was successfully created.'
        else
          render :new, status: :unprocessable_entity
        end
      else
        render :new, alert: 'You have created 9 exams already!'
      end
    end

    def update
      if @level.update(level_params)
        redirect_to dashboard_level_path(@level), notice: 'Exam was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      questions = @level.questions
      exam = @level.exam

      delete_associated_questions(questions)
      @level.destroy
      exam.destroy

      redirect_to dashboard_exams_path, notice: 'Exam was successfully destroyed.'
    end

    private

    def set_level
      @level = Level.find(params[:id])
    end

    def level_params
      params.require(:level).permit(questions_attributes: %i[id question_title first_answer second_answer third_answer
                                                                     correct_answer points _destroy])
    end

    def delete_associated_questions(questions)
      questions.each do |q|
        q.destroy
      end
    end
  end
end

app/controllers/dashboard/pages_controller.rb
module Dashboard
  class PagesController < Dashboard::DashboardController
    before_action :current_user_is_student?

    def home
      @students = User.all.where(student_role: true).count
      # @classrooms = Room.all.where(school_id: current_user.school.id).count
    end

    private

    def current_user_is_student?
      if current_user.student_role?
        redirect_to dashboard_exams_path
      end
    end
  end
end

app/controllers/dashboard/questions_controller.rb
module Dashboard
  class QuestionsController < Dashboard::DashboardController
    before_action :set_question, only: %i[show edit update destroy]

    def index
      @questions = Question.all
    end

    def show; end

    def new
      @questions = Question.new
    end

    def edit; end

    def create
      @questions = Question.new(question_params)

      if @questions.save
        redirect_to @questions, notice: 'Question was successfully created.'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @questions.update(question_params)
        redirect_to @questions, notice: 'Question was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @questions.destroy

      redirect_to dashboard_questions_path, notice: 'Question was successfully destroyed.'
    end

    private

    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:name)
    end
  end
end

app/controllers/dashboard/results_controller.rb
module Dashboard
  class ResultsController < Dashboard::DashboardController
    def index
      # @results = Exam.joins(:results).where(results: {student_id: current_user.i})
      @results = Result.where(student_id: current_user.id)
    end

    def new
      @result = Result.new
      @exam = Exam.find_by(id: params[:exam], school_id: current_user.school_id)
      @questions = @exam.level.questions
    end

    def create
      @result = Result.new(result_params)
      @result.student = current_user
      @result.taken = true

      if @result.save
        redirect_to dashboard_results_url, notice: 'Exam was successfully submitted.'
      else
        render :new, status: :unprocessable_entity
      end
    end

    private

    def result_params
      params.require(:result).permit(%i[grade exam_id])
    end
  end
end

app/controllers/dashboard/rooms_controller.rb
module Dashboard
  class RoomsController < Dashboard::DashboardController
    before_action :set_room, only: %i[show edit update destroy]

    # GET /rooms or /rooms.json
    def index
      @rooms = Room.all
      @room = Room.new
    end

    # GET /rooms/1 or /rooms/1.json
    def show
    end

    # GET /rooms/new
    def new
      @room = Room.new
    end

    # GET /rooms/1/edit
    def edit
    end

    # POST /rooms or /rooms.json
    def create
      @room = Room.new(room_params)

      if @room.save
        redirect_to @room, notice: "Room was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /rooms/1 or /rooms/1.json
    def update
      if @room.update(room_params)
        redirect_to @room, notice: "Room was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /rooms/1 or /rooms/1.json
    def destroy
      @room.destroy

      redirect_to rooms_url, notice: "Room was successfully destroyed."
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
  end
end

app/views/dashboard/exams/index.html.erb
<div class="px-12">
  <h1 class="text-2xl text-black mb-5">Exams</h1>
  <% if @exams.empty? %>
    <% if current_user.teacher_role %>
      <div class="flex justify-center items-center" style="height: calc(100vh - (1rem + 32px))">
        <h1 class="text-xl text-black text-center">You haven't created exams
          yet! <%= link_to "Create one", new_dashboard_level_path, class: "text-indigo-400 underline" %></h1>
      </div>
    <% elsif current_user.student_role %>
      <div class="flex justify-center items-center" style="height: calc(100vh - (1rem + 32px))">
        <h1 class="text-xl text-black text-center">You teacher haven't added exams yet!</h1>
      </div>
    <% end %>
  <% else %>
    <% @exams.each do |exam| %>
      <div class="p-4 bg-white shadow-sm rounded-md mb-4 flex justify-between text-black">
        <% if current_user.teacher_role %>
          <%= link_to exam.title, dashboard_level_path(exam.level.id), class: "text-indigo-500 underline" %>
        <% else %>
          <div class="text-indigo-500 underline"><%= exam.title %></div>
        <% end %>
        <div><%= exam.level.questions.count %> <%= 'Question'.pluralize(exam.level.questions.count) %></div>
        <div><b>Created by:</b> <%= "#{exam.teacher.first_name} #{exam.teacher.last_name}" %></div>
        <div class="flex space-x-1">
          <% if current_user.teacher_role %>
            <%= link_to dashboard_level_path(exam.level.id), class: "border-2 border-indigo-200 rounded-md p-1" do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="h-4 w-4 text-indigo-500">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"
                  />
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/>
              </svg>
            <% end %>
          <% end %>
          <% if current_user.student_role %>
            <%# byebug %>
            <%# taken = exam.results.where(student_id: current_user.id).first %>
            <%# byebug %>
            <%# if taken.taken? %>
<!--              <p class=""><b>Grade:</b> <%#= current_user.results.where(exam_id: exam.id) %></p>-->
            <%# else %>
              <%= link_to "Take Exam", new_dashboard_result_path(exam: exam.id),
                          class: "flex items-center justify-center px-5 py-1 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 mr-2" %>
            <%# end %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/dashboard/exams/show.html.erb
<div class="px-12">
  <h1 class="text-2xl text-black mb-5">Levels of Exam #<%= @exam.id %></h1>
  <% if @levels.empty? %>
    <div class="flex justify-center items-center" style="height: calc(100vh - (1rem + 32px))">
      <h1 class="text-xl text-black text-center">You haven't created exams yet! <%= link_to "Create one", new_dashboard_level_path, class: "text-indigo-400 underline" %></h1>
    </div>
  <% else %>
    <% @levels.each do |level| %>
      <div class="p-4 bg-white shadow-sm rounded-md mb-4 flex justify-between text-black">
        <%= link_to level.title, dashboard_level_path(level), class: "text-indigo-500 underline" %>
        <div>Created by: <%= "#{level.teacher.first_name} #{level.teacher.last_name}" %></div>
        <div class="flex space-x-1">
          <%= link_to dashboard_level_path(level), class: "border-2 border-indigo-200 rounded-md p-1" do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="h-4 w-4 text-indigo-500">
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"
                />
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/>
            </svg>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>