config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
  }

  namespace :dashboard do
    get 'pages/home'
    resources :rooms, only: %i[index]
    resources :exams, only: %i[index]
    resources :levels, except: %i[index]
    resources :questions
    resources :results, only: %i[index new create]
    root to: "pages#home"
  end

  authenticated :user do
    root to: 'dashboard/pages#home', as: 'authenticated_root'
  end

  unauthenticated :user do
    root to: 'pages#home', as: 'unauthenticated_root'
  end
end

app/models/level.rb
class Level < ApplicationRecord
  belongs_to :exam
  belongs_to :teacher, class_name: 'User'
  has_many :questions
  accepts_nested_attributes_for :questions, allow_destroy: true, reject_if: :all_blank
end

app/controllers/dashboard/dashboard_controller.rb
module Dashboard
  class DashboardController < ApplicationController
    before_action :authenticate_user!
    layout 'dashboard'
  end
end

app/controllers/dashboard/exams_controller.rb
module Dashboard
  class ExamsController < Dashboard::DashboardController
    before_action :set_exam, only: %i[show]

    def index
      @exams = current_user.student_role? ? current_user.school.exams - current_user.school.exams.joins(:results).where(results: {student_id: current_user.id, taken: true})
                   : current_user.school.exams.includes(%i[teacher])
    end

    def show
      @levels = @exam.levels
    end

    private

    def set_exam
      @exam = Exam.find(params[:id])
    end
  end
end

app/controllers/dashboard/levels_controller.rb
module Dashboard
  class LevelsController < Dashboard::DashboardController
    load_and_authorize_resource
    before_action :set_level, only: %i[show edit update destroy]

    def index
      @levels = Level.all
    end

    def show; end

    def new
      @level = Level.new
    end

    def edit; end

    def create
      @level = Level.new(level_params)
      @exam = Exam.new(teacher_id: current_user.id)
      school_id = current_user.school.id

      if @exam.can_create_exam?(school_id)
        @exam.school_id = school_id
        @exam.teacher_id = current_user.id
        @exam.save

        @level.exam = @exam
        @level.teacher_id = current_user.id if current_user.teacher_role? || current_user.superadmin_role?

        if @level.save
          redirect_to dashboard_level_url(@level), notice: 'Exam was successfully created.'
        else
          render :new, status: :unprocessable_entity
        end
      else
        render :new, alert: 'You have created 9 exams already!'
      end
    end

    def update
      if @level.update(level_params)
        redirect_to dashboard_level_path(@level), notice: 'Exam was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      questions = @level.questions
      exam = @level.exam

      delete_associated_questions(questions)
      @level.destroy
      exam.destroy

      redirect_to dashboard_exams_path, notice: 'Exam was successfully destroyed.'
    end

    private

    def set_level
      @level = Level.find(params[:id])
    end

    def level_params
      params.require(:level).permit(questions_attributes: %i[id question_title first_answer second_answer third_answer
                                                                     correct_answer points _destroy])
    end

    def delete_associated_questions(questions)
      questions.each do |q|
        q.destroy
      end
    end
  end
end

app/controllers/dashboard/pages_controller.rb
module Dashboard
  class PagesController < Dashboard::DashboardController
    before_action :current_user_is_student?

    def home
      @students = User.all.where(student_role: true).count
      # @classrooms = Room.all.where(school_id: current_user.school.id).count
    end

    private

    def current_user_is_student?
      if current_user.student_role?
        redirect_to dashboard_exams_path
      end
    end
  end
end

app/controllers/dashboard/questions_controller.rb
module Dashboard
  class QuestionsController < Dashboard::DashboardController
    before_action :set_question, only: %i[show edit update destroy]

    def index
      @questions = Question.all
    end

    def show; end

    def new
      @questions = Question.new
    end

    def edit; end

    def create
      @questions = Question.new(question_params)

      if @questions.save
        redirect_to @questions, notice: 'Question was successfully created.'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @questions.update(question_params)
        redirect_to @questions, notice: 'Question was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @questions.destroy

      redirect_to dashboard_questions_path, notice: 'Question was successfully destroyed.'
    end

    private

    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:name)
    end
  end
end

app/controllers/dashboard/results_controller.rb
module Dashboard
  class ResultsController < Dashboard::DashboardController
    def index
      # @results = Exam.joins(:results).where(results: {student_id: current_user.i})
      @results = Result.where(student_id: current_user.id)
    end

    def new
      @result = Result.new
      @exam = Exam.find_by(id: params[:exam], school_id: current_user.school_id)
      @questions = @exam.level.questions
    end

    def create
      @result = Result.new(result_params)
      @result.student = current_user
      @result.taken = true

      if @result.save
        redirect_to dashboard_results_url, notice: 'Exam was successfully submitted.'
      else
        render :new, status: :unprocessable_entity
      end
    end

    private

    def result_params
      params.require(:result).permit(%i[grade exam_id])
    end
  end
end

app/controllers/dashboard/rooms_controller.rb
module Dashboard
  class RoomsController < Dashboard::DashboardController
    before_action :set_room, only: %i[show edit update destroy]

    # GET /rooms or /rooms.json
    def index
      @rooms = Room.all
      @room = Room.new
    end

    # GET /rooms/1 or /rooms/1.json
    def show
    end

    # GET /rooms/new
    def new
      @room = Room.new
    end

    # GET /rooms/1/edit
    def edit
    end

    # POST /rooms or /rooms.json
    def create
      @room = Room.new(room_params)

      if @room.save
        redirect_to @room, notice: "Room was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /rooms/1 or /rooms/1.json
    def update
      if @room.update(room_params)
        redirect_to @room, notice: "Room was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /rooms/1 or /rooms/1.json
    def destroy
      @room.destroy

      redirect_to rooms_url, notice: "Room was successfully destroyed."
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
  end
end

app/views/dashboard/levels/_form.html.erb
<div class="px-12">
  <h1 class="text-2xl text-black mb-3">Create new level</h1>
  <%= form_with(url: dashboard_levels_path, model: level, local: true, class: "w-full overflow-scroll") do |f| %>
    <div class="">
      <div class="nested-fields">
        <% if level.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(level.errors.count, "error") %> prohibited this exam from being saved:</h2>

            <ul>
              <% level.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= f.fields_for :questions, level.questions.build do |questions_form| %>
          <%= render 'question_fields', f: questions_form %>
        <% end %>
        <%= link_to_add_fields "Add Question", f, :questions, class: "px-5 py-1 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600" %>
      </div>
    </div>
    <div class="actions mt-5 flex justify-end">
      <%= f.submit "Create Exam", class: "bg-indigo-500 text-white py-2 px-3 rounded-md cursor-pointer" %>
    </div>
  <% end %>
</div>

app/views/dashboard/levels/_question_fields.html.erb
<div class="p-4 bg-white shadow-sm rounded-md mb-4 questions_fields_container">
  <h3 class="text-lg text-black mb-3 question_counter">Question</h3>
  <div class="flex flex-wrap -mx-3 mb-6">
    <%= f.hidden_field :_destroy %>
    <div class="w-full px-3">
      <%= f.label :question_title, class: "block tracking-wide text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_area :question_title, class: "appearance-none block w-full text-gray-700 border border-indigo-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white h-42" %>
      <p class="text-gray-600 text-xs italic">This question will be shown to student when taking the exam.</p>
    </div>
  </div>
  <div class="flex flex-wrap -mx-3 mb-6">
    <div class="w-full px-3">
      <%= f.label :first_answer, class: "block tracking-wide text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_field :first_answer, class: "appearance-none block w-full text-gray-700 border border-indigo-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" %>
    </div>
  </div>
  <div class="flex flex-wrap -mx-3 mb-6">
    <div class="w-full px-3">
      <%= f.label :second_answer, class: "block tracking-wide text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_field :second_answer, class: "appearance-none block w-full text-gray-700 border border-indigo-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" %>
    </div>
  </div>
  <div class="flex flex-wrap -mx-3 mb-6">
    <div class="w-full px-3">
      <%= f.label :third_answer, class: "block tracking-wide text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_field :third_answer, class: "appearance-none block w-full text-gray-700 border border-indigo-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" %>
    </div>
  </div>
  <div class="flex flex-wrap -mx-3 mb-6">
    <div class="px-3">
      <%= f.label :correct_answer, class: "block tracking-wide text-gray-700 text-sm font-bold mb-2" %>
      <%= f.select :correct_answer, options_for_select([["First answer", 1], ["Second answer", 2], ["Third answer", 3]], selected: f.object.correct_answer), {}, {class: "block text-gray-700 border border-indigo-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white"} %>
    </div>
    <div class="px-3">
      <%= f.label :points, class: "block tracking-wide text-gray-700 text-sm font-bold mb-2" %>
      <%= f.number_field :points, class: "appearance-none block w-full text-gray-700 border border-indigo-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" %>
    </div>
  </div>
  <div>
    <%= link_to "Remove", '#', class: "remove_fields px-5 py-1 border border-red-600 text-sm font-medium rounded-md text-white text-red-600", data: {confirm: "Are you sure you want to delete this question?"} %>
  </div>
</div>

app/views/dashboard/levels/edit.html.erb
<div class="px-12">
  <h1 class="text-2xl text-black mb-3">Edit <%= @level.title %></h1>
    <%= form_with model: @level, url: dashboard_level_path, method: :patch, local: true, class: "w-full overflow-scroll" do |f| %>
    <div class="">
      <div class="nested-fields">
        <% if @level.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@level.errors.count, "error") %> prohibited this room from being saved:</h2>

            <ul>
              <% @level.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= f.fields_for :questions do |questions_form| %>
          <%= render 'question_fields', f: questions_form %>
        <% end %>
        <div class="flex items-center justify-end">
          <%= link_to_add_fields "Add Question", f, :questions, class: "px-5 py-1 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600" %>
        </div>
      </div>
    </div>
    <div class="actions mt-5 flex justify-end">
      <%= f.submit "Update #{@level.title}", class: "bg-indigo-500 text-white py-2 px-3 rounded-md cursor-pointer" %>
    </div>
  <% end %>
</div>

app/views/dashboard/levels/new.html.erb
<% if can_create_level? %>
  <%= render 'dashboard/levels/form', level: @level %>
<% else %>
  <h1 class="text-2xl text-black text-center">You cannot create more than 9 Exams</h1>
<% end %>

app/views/dashboard/levels/show.html.erb
<div class="px-12">
  <div class="flex justify-between items-center mb-5">
    <h1 class="text-black text-2xl"><%= @level.exam.title %></h1>
    <div class="flex items-center">
      <%= link_to "Edit", edit_dashboard_level_path(@level),
                  class: "flex items-center justify-center px-5 py-1 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 mr-2" %>
      <%= link_to "Delete", dashboard_level_path(@level),
                  method: :delete, data: {confirm: "Are you sure you want to delete #{@level.title}?"},
                  class: "flex items-center justify-center px-5 py-1 border border-transparent text-sm font-medium rounded-md text-white bg-red-600" %>
    </div>
  </div>
  <% @level.questions.each_with_index do |question, index| %>
    <div class="p-4 bg-white shadow-sm rounded-md mb-4">
      <div class="flex justify-between items-center mb-3">
        <h3 class="text-lg text-black"><%= question.question_title %></h3>
        <h4 class="text-base text-black">Question <%= index + 1 %></h4>
      </div>
      <ol class="list-decimal pl-10 mb-4">
        <li><%= question.first_answer %></li>
        <li><%= question.second_answer %></li>
        <li><%= question.third_answer %></li>
      </ol>
      <div class="text-green-600">Correct answer: <%= question.correct_answer %></div>
    </div>
  <% end %>
</div>