config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
  }

  namespace :dashboard do
    get 'pages/home'
    resources :rooms, only: %i[index]
    resources :exams, only: %i[index]
    resources :levels, except: %i[index]
    resources :questions
    resources :results, only: %i[index new create]
    root to: "pages#home"
  end

  authenticated :user do
    root to: 'dashboard/pages#home', as: 'authenticated_root'
  end

  unauthenticated :user do
    root to: 'pages#home', as: 'unauthenticated_root'
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :head_teacher, class_name: 'User'
  has_many :students, class_name: 'User'
  # has_many :students, foreign_key: 'student_id', inverse_of: :student
end

app/controllers/dashboard/dashboard_controller.rb
module Dashboard
  class DashboardController < ApplicationController
    before_action :authenticate_user!
    layout 'dashboard'
  end
end

app/controllers/dashboard/exams_controller.rb
module Dashboard
  class ExamsController < Dashboard::DashboardController
    before_action :set_exam, only: %i[show]

    def index
      @exams = current_user.student_role? ? current_user.school.exams - current_user.school.exams.joins(:results).where(results: {student_id: current_user.id, taken: true})
                   : current_user.school.exams.includes(%i[teacher])
    end

    def show
      @levels = @exam.levels
    end

    private

    def set_exam
      @exam = Exam.find(params[:id])
    end
  end
end

app/controllers/dashboard/levels_controller.rb
module Dashboard
  class LevelsController < Dashboard::DashboardController
    load_and_authorize_resource
    before_action :set_level, only: %i[show edit update destroy]

    def index
      @levels = Level.all
    end

    def show; end

    def new
      @level = Level.new
    end

    def edit; end

    def create
      @level = Level.new(level_params)
      @exam = Exam.new(teacher_id: current_user.id)
      school_id = current_user.school.id

      if @exam.can_create_exam?(school_id)
        @exam.school_id = school_id
        @exam.teacher_id = current_user.id
        @exam.save

        @level.exam = @exam
        @level.teacher_id = current_user.id if current_user.teacher_role? || current_user.superadmin_role?

        if @level.save
          redirect_to dashboard_level_url(@level), notice: 'Exam was successfully created.'
        else
          render :new, status: :unprocessable_entity
        end
      else
        render :new, alert: 'You have created 9 exams already!'
      end
    end

    def update
      if @level.update(level_params)
        redirect_to dashboard_level_path(@level), notice: 'Exam was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      questions = @level.questions
      exam = @level.exam

      delete_associated_questions(questions)
      @level.destroy
      exam.destroy

      redirect_to dashboard_exams_path, notice: 'Exam was successfully destroyed.'
    end

    private

    def set_level
      @level = Level.find(params[:id])
    end

    def level_params
      params.require(:level).permit(questions_attributes: %i[id question_title first_answer second_answer third_answer
                                                                     correct_answer points _destroy])
    end

    def delete_associated_questions(questions)
      questions.each do |q|
        q.destroy
      end
    end
  end
end

app/controllers/dashboard/pages_controller.rb
module Dashboard
  class PagesController < Dashboard::DashboardController
    before_action :current_user_is_student?

    def home
      @students = User.all.where(student_role: true).count
      # @classrooms = Room.all.where(school_id: current_user.school.id).count
    end

    private

    def current_user_is_student?
      if current_user.student_role?
        redirect_to dashboard_exams_path
      end
    end
  end
end

app/controllers/dashboard/questions_controller.rb
module Dashboard
  class QuestionsController < Dashboard::DashboardController
    before_action :set_question, only: %i[show edit update destroy]

    def index
      @questions = Question.all
    end

    def show; end

    def new
      @questions = Question.new
    end

    def edit; end

    def create
      @questions = Question.new(question_params)

      if @questions.save
        redirect_to @questions, notice: 'Question was successfully created.'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @questions.update(question_params)
        redirect_to @questions, notice: 'Question was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @questions.destroy

      redirect_to dashboard_questions_path, notice: 'Question was successfully destroyed.'
    end

    private

    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:name)
    end
  end
end

app/controllers/dashboard/results_controller.rb
module Dashboard
  class ResultsController < Dashboard::DashboardController
    def index
      # @results = Exam.joins(:results).where(results: {student_id: current_user.i})
      @results = Result.where(student_id: current_user.id)
    end

    def new
      @result = Result.new
      @exam = Exam.find_by(id: params[:exam], school_id: current_user.school_id)
      @questions = @exam.level.questions
    end

    def create
      @result = Result.new(result_params)
      @result.student = current_user
      @result.taken = true

      if @result.save
        redirect_to dashboard_results_url, notice: 'Exam was successfully submitted.'
      else
        render :new, status: :unprocessable_entity
      end
    end

    private

    def result_params
      params.require(:result).permit(%i[grade exam_id])
    end
  end
end

app/controllers/dashboard/rooms_controller.rb
module Dashboard
  class RoomsController < Dashboard::DashboardController
    before_action :set_room, only: %i[show edit update destroy]

    # GET /rooms or /rooms.json
    def index
      @rooms = Room.all
      @room = Room.new
    end

    # GET /rooms/1 or /rooms/1.json
    def show
    end

    # GET /rooms/new
    def new
      @room = Room.new
    end

    # GET /rooms/1/edit
    def edit
    end

    # POST /rooms or /rooms.json
    def create
      @room = Room.new(room_params)

      if @room.save
        redirect_to @room, notice: "Room was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /rooms/1 or /rooms/1.json
    def update
      if @room.update(room_params)
        redirect_to @room, notice: "Room was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /rooms/1 or /rooms/1.json
    def destroy
      @room.destroy

      redirect_to rooms_url, notice: "Room was successfully destroyed."
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/dashboard/rooms/_form.html.erb
<%= form_with(url: dashboard_rooms_path, model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dashboard/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', dashboard_room_path(@room) %> |
<%= link_to 'Back', dashboard_rooms_path %>

app/views/dashboard/rooms/index.html.erb
<div class="mb-6 flex justify-between items-center">
  <h1 class="text-2xl text-black">Classrooms</h1>
  <%#= link_to 'New Classroom', new_dashboard_room_path, class: "px-3 py-2 text-white bg-indigo-500 rounded-md focus:bg-indigo-600 focus:outline-none" %>
</div>
<div>
  <div class="flex flex-col max-w-full overflow-x-hidden rounded-md shadow-md">
    <table class="overflow-x-auto w-full bg-white">
      <thead class="bg-blue-100 border-b border-gray-300">
      <tr>
        <th class="p-4 text-left text-sm font-medium text-gray-500">Name</th>
        <th class="p-4 text-left text-sm font-medium text-gray-500">Head Teacher</th>
        <th class="p-4 text-left text-sm font-medium text-gray-500">Created Date</th>
        <th class="p-4 text-left text-sm font-medium text-gray-500">Created Time</th>
        <th class="p-4 text-left text-sm font-medium text-gray-500">Enrolled Students</th>
      </tr>
      </thead>
      <tbody class="text-gray-600 text-sm divide-y divide-gray-300">
      <% @rooms.each do |room| %>
      <tr class="bg-white font-medium text-sm divide-y divide-gray-200">
        <td class="p-4 whitespace-nowrap text-indigo-500 underline"><%= room.name %></td>
        <td class="p-4 whitespace-nowrap">
          <%= "#{User.where(id: room.head_teacher_id).map(&:first_name)[0]} #{User.where(id: room.head_teacher_id).map(&:last_name)[0]}" %>
        </td>
        <td class="p-4 whitespace-nowrap"><%= room.created_at.strftime('%d.%m.%Y') %></td>
        <td class="p-4 whitespace-nowrap"><%= room.created_at.strftime('%H:%M') %></td>
        <td class="p-4 whitespace-nowrap"><%= room.students.count %> <%= 'student'.pluralize(room.students.count)  %></td>
<!--        <td class="p-4 whitespace-nowrap">-->
<!--          <div class="flex space-x-1">-->
            <%#= link_to dashboard_room_path(room), class: "border-2 border-indigo-200 rounded-md p-1" do %>
<!--              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="h-4 w-4 text-indigo-500">-->
<!--                <path-->
<!--                  stroke-linecap="round"-->
<!--                  stroke-linejoin="round"-->
<!--                  stroke-width="2"-->
<!--                  d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"-->
<!--                  />-->
<!--                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />-->
<!--              </svg>-->
            <%# end %>
            <%#= link_to edit_dashboard_room_path(room), class: "border-2 border-indigo-200 rounded-md p-1" do %>
<!--              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="h-4 w-4 text-indigo-500">-->
<!--                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />-->
<!--              </svg>-->
            <%# end %>
            <%#= link_to dashboard_room_path(room), method: :delete, class: "border-2 border-red-200 rounded-md p-1", data: { confirm: 'Are you sure?' } do %>
<!--              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="h-4 w-4 text-red-500">-->
<!--                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />-->
<!--              </svg>-->
            <%# end %>
<!--          </div>-->
<!--        </td>-->
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/dashboard/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', dashboard_rooms_path %>

app/views/dashboard/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_dashboard_room_path(@room) %> |
<%= link_to 'Back', dashboard_rooms_path %>