config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
  }

  namespace :dashboard do
    get 'pages/home'
    resources :rooms, only: %i[index]
    resources :exams, only: %i[index]
    resources :levels, except: %i[index]
    resources :questions
    resources :results, only: %i[index new create]
    root to: "pages#home"
  end

  authenticated :user do
    root to: 'dashboard/pages#home', as: 'authenticated_root'
  end

  unauthenticated :user do
    root to: 'pages#home', as: 'unauthenticated_root'
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.superadmin_role?
      can :manage, :all
    end
    if user.teacher_role?
      can :manage, Exam
      can :manage, Level
      can :manage, Question
    end
    if user.student_role?
      can :read, Result
    end
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :schools
end

app/models/exam.rb
class Exam < ApplicationRecord
  before_validation :assign_title
  belongs_to :teacher, class_name: 'User'
  belongs_to :school
  has_one :level
  has_many :results

  validates_presence_of :title

  def numbers_of_exams
    Exam.all.count
  end

  def can_create_exam?(school_id)
    School.find(school_id).exams.count < 9
  end

  private

  def assign_title
    self.title = "Exam #{numbers_of_exams + 1}"
  end
end

app/models/level.rb
class Level < ApplicationRecord
  belongs_to :exam
  belongs_to :teacher, class_name: 'User'
  has_many :questions
  accepts_nested_attributes_for :questions, allow_destroy: true, reject_if: :all_blank
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :level
  validates_presence_of :question_title, :first_answer, :second_answer, :third_answer, :points
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :student, class_name: 'User'
  belongs_to :exam
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :head_teacher, class_name: 'User'
  has_many :students, class_name: 'User'
  # has_many :students, foreign_key: 'student_id', inverse_of: :student
end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :country
  has_many :exams
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, :registerable

  has_many :rooms, foreign_key: 'head_teacher_id', inverse_of: :head_teacher
  has_many :exams, foreign_key: 'teacher_id', inverse_of: :teacher
  has_many :levels, foreign_key: 'teacher_id', inverse_of: :teacher
  has_many :results, foreign_key: 'student_id', inverse_of: :student
  belongs_to :room, optional: true
  belongs_to :school
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number])
  end
end

app/controllers/dashboard/exams_controller.rb
module Dashboard
  class ExamsController < Dashboard::DashboardController
    before_action :set_exam, only: %i[show]

    def index
      @exams = current_user.student_role? ? current_user.school.exams - current_user.school.exams.joins(:results).where(results: {student_id: current_user.id, taken: true})
                   : current_user.school.exams.includes(%i[teacher])
    end

    def show
      @levels = @exam.levels
    end

    private

    def set_exam
      @exam = Exam.find(params[:id])
    end
  end
end

app/controllers/dashboard/pages_controller.rb
module Dashboard
  class PagesController < Dashboard::DashboardController
    before_action :current_user_is_student?

    def home
      @students = User.all.where(student_role: true).count
      # @classrooms = Room.all.where(school_id: current_user.school.id).count
    end

    private

    def current_user_is_student?
      if current_user.student_role?
        redirect_to dashboard_exams_path
      end
    end
  end
end

app/controllers/dashboard/rooms_controller.rb
module Dashboard
  class RoomsController < Dashboard::DashboardController
    before_action :set_room, only: %i[show edit update destroy]

    # GET /rooms or /rooms.json
    def index
      @rooms = Room.all
      @room = Room.new
    end

    # GET /rooms/1 or /rooms/1.json
    def show
    end

    # GET /rooms/new
    def new
      @room = Room.new
    end

    # GET /rooms/1/edit
    def edit
    end

    # POST /rooms or /rooms.json
    def create
      @room = Room.new(room_params)

      if @room.save
        redirect_to @room, notice: "Room was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /rooms/1 or /rooms/1.json
    def update
      if @room.update(room_params)
        redirect_to @room, notice: "Room was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /rooms/1 or /rooms/1.json
    def destroy
      @room.destroy

      redirect_to rooms_url, notice: "Room was successfully destroyed."
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navbar_current_class?(test_path)
    return 'bg-gray-50 text-gray-800 border-indigo-500' if request.path == test_path
    ''
  end

  def link_to_add_fields(name, f, association, style)
    if association && name && f
      new_object = f.object.send(association).klass.new

      id = new_object.object_id
      fields = f.fields_for(association, new_object, child_index: id) do |builder|

        render(association.to_s.singularize + "_fields", f: builder)
      end

      link_to(name, '#', class: "add_fields " + style[:class].to_s, data: {id: id, fields: fields.gsub("\n", "")})
    end
  end

  def can_create_level?
    Exam.all.count < 9
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_sidebar.html.erb
<div class="w-1/6 bg-white rounded p-3 shadow-lg">
  <div class="flex items-center justify-center h-14 border-b">
    <div class="font-medium text-indigo-500">
      Welcome Back <%= "#{current_user.first_name} #{current_user.last_name}" %>
    </div>
  </div>
  <div class="overflow-y-auto overflow-x-hidden flex-grow">
    <ul class="flex flex-col py-4 space-y-1">
      <% if current_user.teacher_role? %>
        <li class="px-5">
          <div class="flex flex-row items-center h-8">
            <div class="text-sm font-light tracking-wide text-gray-500">Menu</div>
          </div>
        </li>
        <li>
          <%= link_to authenticated_root_path, class: "relative flex flex-row items-center h-11 focus:outline-none hover:bg-gray-50 text-gray-600 hover:text-gray-800 border-l-4 border-transparent hover:border-indigo-500 pr-6 #{navbar_current_class?(dashboard_root_path)}" do %>
            <span class="inline-flex justify-center items-center ml-4">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
            </span>
            <span class="ml-2 text-sm tracking-wide truncate">Dashboard</span>
          <% end %>
        </li>
        <li>
          <%= link_to dashboard_rooms_path, class: "relative flex flex-row items-center h-11 focus:outline-none hover:bg-gray-50 text-gray-600 hover:text-gray-800 border-l-4 border-transparent hover:border-indigo-500 pr-6 #{navbar_current_class?(dashboard_rooms_path)}" do %>
              <span class="inline-flex justify-center items-center ml-4">
                  <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z"></path></svg>
                </span>
            <span class="ml-2 text-sm tracking-wide truncate">Classrooms</span>
          <% end %>
        </li>
        <li>
          <%= link_to dashboard_exams_path, class: "relative flex flex-row items-center h-11 focus:outline-none hover:bg-gray-50 text-gray-600 hover:text-gray-800 border-l-4 border-transparent hover:border-indigo-500 pr-6 #{navbar_current_class?(dashboard_exams_path)}" do %>
            <span class="inline-flex justify-center items-center ml-4">
                <svg class="h-4 fill-current" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M0 1.75A.75.75 0 01.75 1h4.253c1.227 0 2.317.59 3 1.501A3.744 3.744 0 0111.006 1h4.245a.75.75 0 01.75.75v10.5a.75.75 0 01-.75.75h-4.507a2.25 2.25 0 00-1.591.659l-.622.621a.75.75 0 01-1.06 0l-.622-.621A2.25 2.25 0 005.258 13H.75a.75.75 0 01-.75-.75V1.75zm8.755 3a2.25 2.25 0 012.25-2.25H14.5v9h-3.757c-.71 0-1.4.201-1.992.572l.004-7.322zm-1.504 7.324l.004-5.073-.002-2.253A2.25 2.25 0 005.003 2.5H1.5v9h3.757a3.75 3.75 0 011.994.574z"></path>
                </svg>
              </span>
            <span class="ml-2 text-sm tracking-wide truncate">Exams</span>
          <% end %>
        </li>
        <li>
          <%= link_to new_dashboard_level_path, class: "relative flex flex-row items-center h-11 focus:outline-none hover:bg-gray-50 text-gray-600 hover:text-gray-800 border-l-4 border-transparent hover:border-indigo-500 pr-6 #{navbar_current_class?(new_dashboard_level_path)}" do %>
              <span class="inline-flex justify-center items-center ml-4">
                  <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01"></path></svg>
                </span>
            <span class="ml-2 text-sm tracking-wide truncate">Create Exam</span>
          <% end %>
      <% end %>
      <% if current_user.student_role? %>
        <li class="px-5">
          <div class="flex flex-row items-center h-8">
            <div class="text-sm font-light tracking-wide text-gray-500">Tasks</div>
          </div>
        </li>
        <li>
          <%= link_to dashboard_exams_path, class: "relative flex flex-row items-center h-11 focus:outline-none hover:bg-gray-50 text-gray-600 hover:text-gray-800 border-l-4 border-transparent hover:border-indigo-500 pr-6 #{navbar_current_class?(dashboard_exams_path)}" do %>
            <span class="inline-flex justify-center items-center ml-4">
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01"></path></svg>
              </span>
            <span class="ml-2 text-sm tracking-wide truncate">Available Exams</span>
          <% end %>
        </li>
        <li>
          <%= link_to dashboard_results_path, class: "relative flex flex-row items-center h-11 focus:outline-none hover:bg-gray-50 text-gray-600 hover:text-gray-800 border-l-4 border-transparent hover:border-indigo-500 pr-6 #{navbar_current_class?(dashboard_results_path)}" do %>
              <span class="inline-flex justify-center items-center ml-4">
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4"></path></svg>
              </span>
            <span class="ml-2 text-sm tracking-wide truncate">Results</span>
          <% end %>
        </li>
      <% end %>
      <li class="px-5">
        <div class="flex flex-row items-center h-8">
          <div class="text-sm font-light tracking-wide text-gray-500">Settings</div>
        </div>
      </li>
      <li>
        <%= link_to edit_user_registration_path, class: "relative flex flex-row items-center h-11 focus:outline-none hover:bg-gray-50 text-gray-600 hover:text-gray-800 border-l-4 border-transparent hover:border-indigo-500 pr-6" do %>
            <span class="inline-flex justify-center items-center ml-4">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path></svg>
            </span>
          <span class="ml-2 text-sm tracking-wide truncate">Profile</span>
        <% end %>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete, class: "relative flex flex-row items-center h-11 focus:outline-none hover:bg-gray-50 text-gray-600 hover:text-gray-800 border-l-4 border-transparent hover:border-indigo-500 pr-6" do %>
            <span class="inline-flex justify-center items-center ml-4">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path></svg>
            </span>
          <span class="ml-2 text-sm tracking-wide truncate">Logout</span>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/_toastr.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
      <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>');
      <% end %>
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YesEu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/toastr" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YesEu</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render "layouts/toastr" %>
<div class="flex flex-wrap bg-gray-100 w-full h-screen">
  <%= render 'layouts/sidebar' %>
  <div class="w-5/6 h-screen overflow-scroll">
    <div class="py-8 px-8 text-gray-500">
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>